name: Playwright Tests with Allure

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  workflow_dispatch:
  schedule:
    - cron: '45 6 * * *'   # 2:45 PM PH time

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Setup Playwright browsers automatically
      - uses: microsoft/playwright-github-action@v1
        with:
          browsers: all

      # Install Allure reporter
      - run: npm install --save-dev allure-playwright

      # Run tests with Allure reporter
      - run: npx playwright test --reporter=line,allure-playwright

      # Install Allure CLI
      - run: npm install -g allure-commandline

      # Generate HTML Allure report
      - run: allure generate allure-results --clean -o allure-report

      # Upload report
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
